GET http://localhost:8001
Accept: application/json
###

GET http://localhost:8001/services/b_and_h_service
Accept: application/json
###

POST http://localhost:8000/lxp2
Content-Type: application/json

{
  "contacts": [
    {
      "profile": {
        "name": "kerry Fisher"
      },
      "wa_id": "1235454633"
    }
  ],
  "message": [
    {
      "from": "1235454633",
      "id": "NSJAHSUASKnsiuasgaskadsjnds",
      "timestamp": "151894235",
      "text": {
        "body": "hi dbs '; insert"
      },
      "type": "text"
    }
  ]
}

###
POST http://localhost:8000/lxp2
Content-Type: application/json

{
  "org.matrix.msc1767.text": "text",
  "body": "hi dbs '; insert",
  "msgtype": "m.text",
  "channel": "wechatminiapp",
  "is_integration_template": false
}

